name: Coverage

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - "*"
jobs:
  coverage:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Setup SSH to install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      # - name: Install dependencies
      #   if: steps.cache-node-modules.outputs.cache-hit != 'true'
      #   run: npm ci
      
      # - name: Run Sol Coverage
      #   run: npm run coverage
      
      # - name: Publish to Codecov.io
      #   run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}