name: Subgraph

on:
  push:
    branches:
      # long-lived branches
      - master
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Setup SSH to install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Truffle Compile
        run: npm run compile

      ### Subgraph Lint ###
      - name: Cache Subgraph node modules
        id: cache-subgraph-node-modules
        uses: actions/cache@v2
        with:
          path: subgraph/node_modules
          key: subgraph-node-modules-${{ hashFiles('subgraph/package-lock.json') }}

      - name: Setup SSH to install Subgraph dependencies
        if: steps.cache-subgraph-node-modules.outputs.cache-hit != 'true'
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Subgraph dependencies
        if: steps.cache-subgraph-node-modules.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: subgraph

      - name: Generate subgraph files
        run: npm run codegen
        working-directory: subgraph

      - name: Build subgraph
        run: npm run build
        working-directory: subgraph
