name: Test

on:
  push:
    branches:
      # long-lived branches
      - master
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12.22.x'

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package.json') }}

      - name: Setup SSH to install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Compile Solidity Contracts
        run: npm run compile

      - name: Run Tests
        run: npm test